version: '3'

services:
  server:
    build: .
    volumes:
      - ./sockets:/app/sockets
    command: server.py
  client:
    build: .
    volumes:
      - ./sockets:/app/sockets
    command: client.py
    depends_on:
      - server
